// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rloinumgazcdfmhocwoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsb2ludW1nYXpjZGZtaG9jd295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTEwNDcsImV4cCI6MjA3MjM2NzA0N30.cHGFMO8doJ7MseC8J0SuBYCvqAggw6kkge7gTEgU_s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});